/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.codyoss.springcloudavro.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InputMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2010217975400590922L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InputMessage\",\"namespace\":\"com.github.codyoss.springcloudavro.avro\",\"fields\":[{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InputMessage> ENCODER =
      new BinaryMessageEncoder<InputMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InputMessage> DECODER =
      new BinaryMessageDecoder<InputMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<InputMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<InputMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InputMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this InputMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a InputMessage from a ByteBuffer. */
  public static InputMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InputMessage() {}

  /**
   * All-args constructor.
   * @param message The new value for message
   */
  public InputMessage(java.lang.String message) {
    this.message = message;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Creates a new InputMessage RecordBuilder.
   * @return A new InputMessage RecordBuilder
   */
  public static com.github.codyoss.springcloudavro.avro.InputMessage.Builder newBuilder() {
    return new com.github.codyoss.springcloudavro.avro.InputMessage.Builder();
  }

  /**
   * Creates a new InputMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InputMessage RecordBuilder
   */
  public static com.github.codyoss.springcloudavro.avro.InputMessage.Builder newBuilder(com.github.codyoss.springcloudavro.avro.InputMessage.Builder other) {
    return new com.github.codyoss.springcloudavro.avro.InputMessage.Builder(other);
  }

  /**
   * Creates a new InputMessage RecordBuilder by copying an existing InputMessage instance.
   * @param other The existing instance to copy.
   * @return A new InputMessage RecordBuilder
   */
  public static com.github.codyoss.springcloudavro.avro.InputMessage.Builder newBuilder(com.github.codyoss.springcloudavro.avro.InputMessage other) {
    return new com.github.codyoss.springcloudavro.avro.InputMessage.Builder(other);
  }

  /**
   * RecordBuilder for InputMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InputMessage>
    implements org.apache.avro.data.RecordBuilder<InputMessage> {

    private java.lang.String message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.codyoss.springcloudavro.avro.InputMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InputMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.codyoss.springcloudavro.avro.InputMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.message)) {
        this.message = data().deepCopy(fields()[0].schema(), other.message);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.github.codyoss.springcloudavro.avro.InputMessage.Builder setMessage(java.lang.String value) {
      validate(fields()[0], value);
      this.message = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.github.codyoss.springcloudavro.avro.InputMessage.Builder clearMessage() {
      message = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InputMessage build() {
      try {
        InputMessage record = new InputMessage();
        record.message = fieldSetFlags()[0] ? this.message : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InputMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<InputMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InputMessage>
    READER$ = (org.apache.avro.io.DatumReader<InputMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
